server:
  servlet:
    context-path: /sell
spring:
  profiles:
    active: dev

#---
#spring:
#  profiles: dev
#  servlet:
#    multipart:
#      # 设置文件最大值
#      max-file-size: 40MB
#      # 设置请求最大值
#      max-request-size: 40MB
#  datasource:
##    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    open-in-view: false
#    show-sql: true
#  jackson:
#    # 配置字段值为null时，不返回字段
#    default-property-inclusion: non_null
#    time-zone: GMT+8
#  redis:
#    database: 0 # Redis数据库索引（默认为0）
#    host: 127.0.0.1 # Redis服务器地址
#    port: 6379 # Redis服务器连接端口
#    password:  # Redis服务器连接密码（默认为空）
#    max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
#    max-wait: 5 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    max-idle: 10 # 连接池中的最大空闲连接
#    min-idle: 10 # 连接池中的最小空闲连接
#    timeout: 10000 # 连接超时时间（毫秒）
## 模板引擎1 thymeleaf
##  thymeleaf:
##    # 开发过程中建议关闭cache
##    cache: false
##    # 模板文件前缀
##    prefix: classpath:/templates/
##    # 模板文件后缀
##    suffix: .html
## 模板引擎2 freemarker
#  freemarker:
#    # 模板目录
#    template-loader-path: classpath:/templates/
#    # 字符集
#    charset: utf-8
#    # 关闭模板缓存，方便测试
#    cache: false
#    # 模板文件后缀
#    suffix: .ftl
#
#server:
#  port: 8080
#logging:
#  level:
#    com.o2ii.sell.mapper: trace # 打印mybatis执行的sql
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#
## 我的测试号
#wechat:
#  appId: wx8e61a539e50ac0ef
#  appSecret: 9a77386f2b9cdfcda5d573b9849b5bc4
#base-config:
#  domains:
#    base-domain: http://base.nat300.top
#paths:
#  file:
#    image: E:\workspace\java\storage\files\images\